### ISSUE TITLE
Mutation observer broken

### ISSUE THREAD

**Issue by snellingio** [ryangjchandler/dab#30]
Introduced in https://github.com/ryangjchandler/dab/pull/27

```
index.js:199 Uncaught (in promise) TypeError: n is not a function
    at index.js:199
    at index.js:191
    at Array.map (<anonymous>)
    at d (index.js:191)
    at index.js:23
    at Map.forEach (<anonymous>)
    at MutationObserver.<anonymous> (index.js:22)
```

The example of adding a counter is broken

**Comment by ryangjchandler** [comment]
@snellingio Will be tackling this in next release (after renaming, etc).
